### ISSUE TITLE
[Anon] Bug report: Nurgle - BB16.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#11]
**File:** Nurgle - BB16.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** Yes

**Description:** Hi, battleScribers

I just been building my nurgle team & i have notice there is no mutation skills option under skill section for them, this is one of the main benfits of using a nurgle team. I can edit other skills name in the mean time to represent them but that is extra messing around, time consuming & could get confusing. Im guessing other teams that can have mutations are the same but i haven't checked them. It something small but it would be very handy if this could be up dated to have them as an option. I can't see any other issues with this team rosta. I hope this makes sense, if you need/want any more info or feedback please do email me Rich1982_1@hotmail.com 

Many thanks 
Rich

**Comment by xerusjoe** [comment]
I'll attempt to fix that as I'm updating new Star Players. I'll also check to see if any other team has this issue.

**Comment by xerusjoe** [comment]
I've fixed it. Will be in the next update.
It should function the same as any other skill, 20k with a Doubles check box.
