### ISSUE TITLE
[Anon] Bug report: Chaos Renegades - BB16.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#15]
**File:** Chaos Renegades - BB16.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** You can only have 1 dark elf renegade, doesn't warn about that

**Comment by xerusjoe** [comment]
Thanks for that catch. Fixing it now, and it will be fixed in the next update.
