### ISSUE TITLE
[Anon] Bug report: Underworld Denizens - BB16.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#16]
**File:** Underworld Denizens - BB16.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Glart Smashrip Star Player (cost 190,000 - I.e. not Glart Smashrip Jnr) is listed as Move 4 and Strength 5.  It should be Move 5 and Strength 4.

**Comment by xerusjoe** [comment]
Thanks. Found it was this was in the Skaven file as well. Both have been adjusted and will be live with release 1.1.8.2.
