### ISSUE TITLE
[Anon] Bug report: Wood Elves - BB16.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#17]
**File:** Wood Elves - BB16.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** When choosing a strength skill in a treeman, when you open the menu to select the skill, passing skills appear instead of strength skills

**Comment by xerusjoe** [comment]
Thanks for the catch.

Found the issue. It seems all Strength Skills for the entire team were set as passing.
Will be fixed when the next update goes live.
