### ISSUE TITLE
Blood Bowl Release Thread

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/bloodbowl#26]
This Thread is for Release Comments.

**Comment by DrTobogganMD** [comment]
/release bump=minor

Spike Issue 9 - The Old World Alliance Arrives!

**Comment by amis92** [comment]
@DrTobogganMD I've made #27 to add what you need here. :)

**Comment by DrTobogganMD** [comment]
Thanks!

**Comment by DrTobogganMD** [comment]
/release

Spike Issue 9 - 2nd Attempt!

**Comment by DrTobogganMD** [comment]
/release

Smashin Da Orc Bugs!

**Comment by DrTobogganMD** [comment]
/release
Dark Elves Have Rules Too!
