### ISSUE TITLE
[Anon] Bug report: Orcs - BB16.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#28]
**File:** Orcs - BB16.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I get a notifaction egen i apply cas or MVPspp on my black orcs that says i have too many selections of black orc blockers even IF i only have the 4 allowed.

**Comment by xerusjoe** [comment]
That is interesting. It appears on any of the SPP options.
