### ISSUE TITLE
BloodBowl Second Season release date?

### ISSUE THREAD

**Issue by aljones15** [BSData/bloodbowl#31]
Has battle scribe been updated to contain [Blood Bowl Season 2](https://www.games-workshop.com/en-US/Blood-Bowl-Rulebook-english-2020) rules?

My apologies if this is a redundant issue.

**Comment by xerusjoe** [comment]
It is being worked on by a newer member since November 25th. Unfortunately, I don't have the time to commit to it currently, so I'm unsure of the progress being made.

**Comment by shaner11** [comment]
I would be happy to help speed things up, would be good to have ready for a league I'm planning. If whoever is working on the data could share their progress and get in touch on the Discord so we could split the work I can get started.

**Comment by bhammonds** [comment]
Hey, any update on this, I can see that you guys are hard at work - the branch is now 49 commits behind master, any timeline as to when these are going to be merged and released? 
Happy to support the community where possible

**Comment by shaner11** [comment]
I have been working on the update over the past few months in drips and drabs, and I'm at the stage where the hard stuff is out of the way. I'm currently smashing out the team updates and will probably be getting the inducements from the core book as well as Death Zone ready for an initial release.

I do want to add some of the other rules in (e.g. custom mercenaries) but those are likely to be worked on after the core stuff is out.
