### ISSUE TITLE
[Anon] Bug report: Nurgle.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#40]
**File:** Nurgle.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The rotter only cost 35k, not 40k. At least it’s in the rules, don’t know if there is a faq which states other point costs

**Comment by bitemytail** [comment]
Using the v3.0.0 release from Jul 8m 2021 (9:40:54 PM), I'm seeing Nurgle rotters as costing 40k.
