### ISSUE TITLE
Morg'n'Torg wrong cost in snotlings

### ISSUE THREAD

**Issue by dumdrak** [BSData/bloodbowl#54]
Morg'n'Torg wrong cost 340k in snotlings, it has to cost 390k 

**To Reproduce**
add Morg as inducements

**Expected behavior**
Morg costs 390k

**Device and data (please complete the following information):**
 - OS: android 11
 - BattleScribe version 2.03.25.338
 - Release version 3.3.1

**Comment by shaner11** [comment]
Looking at the FAQ, the cost for Morg 'n' Thorg has been changed to 380k, not 390k. I have updated to that value as it seems to be correct. Please reopen the issue with further detail on where the extra 10k comes from if this is incorrect.

**Comment by dumdrak** [comment]
Hi,

with the new release, the cost of Morg'n'Thorg have no changed. It shows 340k.

Also in inducements when you add a new one there is 2 diferents "inducements" and "Star Players" options

Both things happens in the others teams (test in snotlings, lizzarmen, necromantic horror, nurgle)

**Comment by shaner11** [comment]
I've checked all of the teams mentioned on my end and I am not seeing anything like you described. Would you be able to send me a screenshot? It might help me figure out what the issue is.

**Comment by dumdrak** [comment]
I updated the data deleting existing data.

Teams created after the update work correctly. Teams created in older version are updated and work fine.

Teams edited in my inconsitent version work worse. Will have to manually recreate them.

thank you for your time

**Comment by shaner11** [comment]
The issue should be resolved, see #57 for more details if you are interested in what happened. Playing around with things on your end and letting me know the results was what solved this one, so a massive thanks for that.
