### ISSUE TITLE
[Anon] Bug report: Norse.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#55]
**File:** Norse.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The primary upgrades for the Valkyrie in the Norse Blood Bowl team is incorrect. When 'voewed' it is corect as AGP, but when attempting to pick a chosen primary skill as the first advamcement the skills available are GPS. Therefore, strength skills should be taken out of the options available and replaced with agility skills.

**Comment by Cavlery** [comment]
Has this inadvertently removed advancements altogether for the Norse blood bowl team?

**Comment by shaner11** [comment]
It shouldn't have, I can get advancements on Norse teams from my end. Can you give me further details/screenshots so I can look into it?

**Comment by shaner11** [comment]
The issue should be resolved in the update I've just pushed, see #57 for more details if you are interested in what happened

**Comment by Cavlery** [comment]
Thanks for this, but on the advancements for the Valkyrie the primary
skills available for a random primary are still GPS instead of AGP.
