### ISSUE TITLE
Scyla Anfingrimm missing for Khorne

### ISSUE THREAD

**Issue by cartag** [BSData/bloodbowl#60]
**Describe the bug**
Scyla Anfingrimm is not showing properly for Khorne teams. Checking the GST, this: 
![image](https://user-images.githubusercontent.com/4388344/172737517-20bf6de6-3b3e-41c1-ae03-f5421cd04fcd.png)

should look like this: 
![image](https://user-images.githubusercontent.com/4388344/172737558-e91eb162-0251-4f36-bd9a-200f0e5aeb37.png)

**To Reproduce**
1. Create new Khorne team
2. Add Star Players to roster
 
**Expected behavior**
Scyla Anfingrimm should be visible
 
**Screenshots**
![image](https://user-images.githubusercontent.com/4388344/172737314-6365b9e6-1201-4998-bc7c-b58a67655b9f.png)

**Comment by shaner11** [comment]
Both Max Spleenripper and Scylla Anfingrimm were missing from the list for Khorne teams (although for a different reason to the one shown, you seem to have an old version of the files). They should appear as of the latest update.
