### ISSUE TITLE
Dungeon Bowl Team Touchdown SPP is incorrect

### ISSUE THREAD

**Issue by dino340** [BSData/bloodbowl#69]
Dungeon Bowl changes the SPP gained from a TD from 3 to 5 as there is only a single TD in a game, currently Touchdowns for Dungeon Bowl teams earn 3 Total SPP. If possible modifying the number of SPP gained from a TD on a dungeon bowl team to 5.

**Comment by shaner11** [comment]
I've fixed this in the Spike #15 update that will go live with the books release next weekend.
