### ISSUE TITLE
Ogre team - Gnoblar Linemen cost missing

### ISSUE THREAD

**Issue by FabledAlpaca** [BSData/bloodbowl#73]
The TV cost of the Gnoblar Linemen is 0 when it should be 15,000 TV

**Comment by shaner11** [comment]
The TV of Gnoblar Linemen is functioning as intended. The default game type for Blood Bowl rosters is League play, and the total cost of players and inducements is meant to reflect the teams CTV. Ogre teams are affected by the Low Cost Linemen special rule, which makes their linemen cost 0 Gold for the purposes of CTV. If you are playing an exhibition match and require the cost of linemen to be reflected in the teams CTV, you can select 'Exhibition' as the game type in the 'Pre-Match Setup' section of the roster.
