### ISSUE TITLE
Blood Bowl Bug Report 18/09/23

### ISSUE THREAD

**Issue by Fanged-Cutie** [BSData/bloodbowl#74]
**Describe the bug**
For Blood Bowl; there is a typo in one of the skill trees. Furthermore; the Slann team is missing the Dodge skill.

**To Reproduce**
Typo
1. Create a 'Humans Team' Standard Roster with -1 in all 'Cost Limit' values
2. Click on 'Game Type', select 'Exhibition'
3. Add a 'Thrower' player, click the 'Advancements' box and click 'Chosen Primary Skill' in the drop down
4. In the 'Primary Skills' section, the 'Passing' skills are mislabled 'Passsing'

Missing Dodge on Slann Teams
1. Create a 'Slann (NAF)' Standard Roster with -1 in all 'Cost Limit' values
2. Click on 'Game Type', select 'Exhibition'
3. Add a 'Catcher' or 'Blitzer' player, click the 'Advancements' box and click 'Chosen Primary Skill' in the drop down
4. Click on the '[A]gility' Skills Dropdown
6. There is no option for the 'Dodge' skill

**Expected behavior**
The typo needs a correction; the 'Dodge' skill should be present in the Slann Agility Advancement section.

**Screenshots**
![image](https://github.com/BSData/bloodbowl/assets/145353943/a4be7bee-271a-40fd-8480-0fa65a023f7f)
![image](https://github.com/BSData/bloodbowl/assets/145353943/1c11724d-6b9c-4618-8815-ef20749bf58e)

**Device and data (please complete the following information):**
 - OS: Windows 10
 - App being used to create lists: New Recruit
 - App version: New Recruit v225
 - Data release version: Slann revision 6

**Comment by shaner11** [comment]
These errors have been fixed in update 3.7
