### ISSUE TITLE
Amazon Blitzer is missing the Hit and Run skill

### ISSUE THREAD

**Issue by cogpunk** [BSData/bloodbowl#75]
**Describe the bug**
The Amazon Blitzer is missing the Hit and Run skill

**To Reproduce**
1. Create an Amazon Team
2. Add a Piranha Warrior Blitzer
3. View the roster
4. Piranha Warrior Blitzer only has Dodge & Jump Up skills, Hit and Run is missing from both the player's entry and the Selection Rules

**Expected behavior**
The Hit and Run skill should be present both the Blitzer's entry and the Selection Rules

**Screenshots**

[Amazon's Roster.pdf](https://github.com/BSData/bloodbowl/files/12784610/Amazon.s.Roster.pdf)

**Device and data (please complete the following information):**
 - OS: macOS
 - App being used to create lists: Battlescribe 
 - App version: 2.03.21
 - Data release version v35

**Additional context**

**Comment by shaner11** [comment]
Fixed has been applied in update 3.7
