### ISSUE TITLE
[Anon] Bug report: Orcs.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#78]
**File:** Orcs.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The roster information for the orc thrower is incorrect. The thrower does not have the block ability. The thrower has sure hands, pass and animosity(all team-mates).

**Comment by MorrisonSWE** [comment]
Can confirm the issue.
