### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by xerusjoe** [BSData/bloodbowl#8]
I'd like to join in order to assist another person in updating the Blood Bowl files to be in line with the 2016 version of the game. The last updates to the files were in 2014 via the Living Rulebook, which a number of things have changed.

**Comment by amis92** [comment]
Hello, @xerusjoe .
Please accept the invitation in the email or on https://github.com/BSData/bloodbowl/invitations . Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
