### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Zappline** [BSData/bloodbowl#9]
Hi. I have updated the LRB6 with the latest ruleset from GW I hope I could join you so I can upload it so everyone can enjoy it :D

**Comment by amis92** [comment]
Hello, @Zappline  .
Please accept the invitation in the email. Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!

PS I see your repo, and I see .catz files. Please take a good read through Developer Guide!
